name: Privacy & Quality Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  privacy-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Privacy Scan
      run: |
        echo "Scanning for personal information..."
        # Check for common personal info patterns
        if grep -r "[personal_name_patterns]" . --exclude-dir=.git; then
          echo "❌ Personal information detected!"
          exit 1
        fi
        
        if grep -r "@[a-zA-Z0-9.-]*\.com" . --exclude-dir=.git | grep -v "noreply"; then
          echo "❌ Email addresses detected!"
          exit 1
        fi
        
        echo "✅ Privacy scan passed"
    
    - name: Framework Validation
      run: |
        echo "Validating framework structure..."
        required_files=("README.md" "LICENSE" "CONTRIBUTING.md" "CODE_OF_CONDUCT.md")
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Missing required file: $file"
            exit 1
          fi
        done
        echo "✅ Framework validation passed"
